name: FreeSkills
description: "Freeskill made by raghavan android & iso"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  #Ui
  flutter_native_splash: ^2.4.1
  dots_indicator: ^3.0.0
  card_slider: ^1.0.5
  fl_chart: ^0.68.0
  flutter_slidable: ^3.1.0
  material_design_icons_flutter: ^7.0.7296
  scaffold_gradient_background: any
  toastification: 2.0.0
  google_nav_bar: 5.0.6
  carousel_slider: 4.2.1
  cupertino_icons: ^1.0.8
  timelines: 0.1.0



  #language
  easy_localization: 3.0.7
  easy_localization_loader: 2.0.2

  #info
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  flutter_screenutil: 5.9.3

  #utils
  preload_page_view: 0.2.0
  firebase_core: any
  firebase_auth: ^5.1.2
  youtube_player_flutter: any
  google_generative_ai: ^0.4.3
  palette_generator: ^0.3.3+4
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^14.2.1

  #Network
  http: ^1.2.1
  flutter_cached_pdfview: 0.4.2


  #disabled
  # miniplayer: ^1.0.1
  # pod_player: ^0.2.2
  # modern_player: ^0.1.0
  # youtube_shorts: ^4.0.2
  # flutter_animate: 4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  #flutter_launcher_icons: 0.13.1
  # flutter_lints: 4.0.0




flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/icon/
    - assets/translations/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf

